### ISSUE TITLE
EntityMetadataNotFound: No metadata for "User" was found. && I found that question in latest issues but i didnt see any solution, that helps me

### ISSUE THREAD

**Issue by ipirm** [w3tecch/typeorm-seeding#105]
My ormconfig.ts

    type: 'postgres',
    host: "localhost",
    port: 5432,
    username: 'postgres',
    password: "root",
    database: "birji_db",
    entities: ["dist/database/**/*.entity.js"],
    factories: [ "dist/database/factories/**/*.js" ],
    seeds: [ "dist/database/seeds/**/*.js"],
    migrations: ["dist/migration/*.js"],
    migrationsRun: true,
    synchronize: true,
    logging: true,
    cli: {
        migrationsDir: 'src/database/migrations',
    }

My structure 
![image](https://user-images.githubusercontent.com/48025760/101969040-b0b01980-3c3b-11eb-98d5-fb5f0bce74a3.png)

What hapens

тЭМ  Could not save entity
EntityMetadataNotFound: No metadata for "User" was found.
    at new EntityMetadataNotFoundError (E:\projects\birji-backend\src\error\EntityMetadataNotFoundError.ts:10:9)
    at Connection.getMetadata (E:\projects\birji-backend\src\connection\Connection.ts:337:19)
    at E:\projects\birji-backend\src\persistence\EntityPersistExecutor.ts:76:55
    at Array.forEach (<anonymous>)
    at EntityPersistExecutor.<anonymous> (E:\projects\birji-backend\src\persistence\EntityPersistExecutor.ts:70:30)
    at step (E:\projects\birji-backend\node_modules\typeorm\node_modules\tslib\tslib.js:141:27)
    at Object.next (E:\projects\birji-backend\node_modules\typeorm\node_modules\tslib\tslib.js:122:57)
    at E:\projects\birji-backend\node_modules\typeorm\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (E:\projects\birji-backend\node_modules\typeorm\node_modules\tslib\tslib.js:111:16)
├Ч Could not run the seed CreateUsers!
Error: Could not save entity
    at EntityFactory.<anonymous> (E:\projects\birji-backend\node_modules\typeorm-seeding\src\entity-factory.ts:52:15)
    at step (E:\projects\birji-backend\node_modules\tslib\tslib.js:140:27)
    at Object.throw (E:\projects\birji-backend\node_modules\tslib\tslib.js:121:57)
    at rejected (E:\projects\birji-backend\node_modules\tslib\tslib.js:112:69)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! birji-backend@0.0.1 seed:run: `ts-node ./node_modules/typeorm-seeding/dist/cli.js seed -n src/database/orm.config.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the birji-backend@0.0.1 seed:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2020-12-12T01_31_55_625Z-debug.log

**Comment by ipirm** [comment]
Dist structure
![image](https://user-images.githubusercontent.com/48025760/101969153-4fd51100-3c3c-11eb-965c-68557a38df2d.png)
 Git: https://github.com/ipirm/birji-new-backend

**Comment by i-kk** [comment]
At first glance you might need to use src/ folder and cover both entity.ts and entity.js 

Something similar to:
```
entities: ["src/database/**/*.entity{.ts,.js}"],
factories: [ "src/database/factories/**/*{.ts,.js}" ],
seeds: [ "src/database/seeds/**/*{.ts,.js}"],
migrations: ["src/migration/*{.ts,.js}"],
```

**Comment by shahabgohar** [comment]
@ipirm 
Hello, i am able to solve this. your error suggest that it is looking for the metadata which is provided when you used annotations in your entity class (probably in user.entity.ts) with .ts. what you need to do is to change the location of entities
just like this
`entities: ['src/**/*.entity{.ts,.js}']`
also point your seeders and migrations to the ts files too

**Comment by KRTirtho** [comment]
Using Glob-path for dynamically requiring dependencies in Nodejs was & is always a bad thing to do. I don't know why _typeorm_  & related libraries still follows this practice even though it was **strictly forbidden many times**
Instead of using glob-paths, directly providing the dependencies by manually importing them is & should be much more preferred. So replace your entities field like so in the `ormconfig.js` or `ormconfig.ts`

```js
import EntityName from "./path/to/entity/file"
import OtherEntityName from "./path/to/other/entity/file"

const config = {
//....
  entities: [
     EntityName,
     OtherEntityName,
  // other entities
  ],
//....
}
```

I wish `typeorm-seeding` also supported providing factories & seeds like this away (safest way). This is applicable for both Typescript & JavaScript projects

**Comment by jorgebodega** [comment]
First of all, this is an open source library, so **please be respectful** and propose your changes into a PR.

I'm disagree with you about glob path, so if you have an article or something talking about this, will be great if you can share with us. But I completely prefer to use glob path to import this kind of files, for some reasons:

1. Allow users to define multiple entities in one line
2. Allow users to define a common naming pattern to files
3. Simplify orm config

I don't think *explicit* import will solve anything here, but I'm open to any other idea

**Comment by KRTirtho** [comment]
First of all,
- Pointing out lacking features of a project/library isn't disrespectful
- It's not important that everyone has enough time & patience to contribute to a project & then point out lackings

Now, the reasons why GlobPath should be avoided for requiring/importing files:
- Nightmare for Typescript/ESM/ESNext based projects since they do support dynamic imports but asynchronously which is not really useful until top-level `await` support roll out in Node/Browsers like Deno
- Even though TSC's `esModuleInterop` is able/tries to fix conflicts between CommonJS & ESM imports but JS based project (specially babel based) struggles in this case. Though some babel plugins allows to do so
- There's no way to know if a file matching the glob pattern is actually exporting the intended component/class/function etc
- No Type Safety which completely destroys the meaning to use Typescript or similar approach
- TSC throws error when an unused typescript file is importing something. It's super hard to compile ES6 to CommonJS when using import statement outside a (unused) module for TSC/babel

There's a whole lot of other points to not use globpath for this kind of tasks. It's a shortcut to avoid minor manual labour in exchange of unsafe code & unrecognizable bugs (in current context)

Some details presented here could & might be wrong

**Comment by jorgebodega** [comment]
I think the way you said this is disrespectful
> I don't know why typeorm & related libraries still follows this practice even though it was strictly forbidden many times

And I'm not sure those problems are enough reasons to change how this works. All of them are problems related to *this* library, but for those who use this library are not. Type-safety is working because seeders and entities must fulfill an interface.

Problems related to importing files using glob pattern should raise on applitacion startup and is responsibility of the user to maintain a proper way to name those files.

Again, if you are so sure that your way is better, please open an issue or a PR with examples.
