### ISSUE TITLE
Faker library incident

### ISSUE THREAD

**Issue by bartosjiri** [w3tecch/typeorm-seeding#204]
Looks like the [Faker.js](https://github.com/marak/Faker.js/) library has been either compromised or discontinued in a strange manner. 

I believe it would be the best to replace this library, since it is provided as a parameter into entity factories. What are some suitable alternatives?

**Comment by jorgebodega** [comment]
Yes, I saw the incident. Quite strange.

In this library, there is no solution, since it cannot be deployed. The only workaround is to use `faker` on version `5.5.3`, the last stable one, as an independent module:

```typescript
import * as faker from 'faker' // USE THIS
...
define(Pet, (faker: typeof Faker) => { // DO NOT USE THIS
  ...
})
```

`faker` could be installed with `npm i faker@5.5.3` since is still available on NPM registries

**Comment by bartosjiri** [comment]
Closing in favor of #201
