### ISSUE TITLE
Module aliases are not resolved

### ISSUE THREAD

**Issue by Shub1427** [w3tecch/typeorm-seeding#29]
Getting error: `Error: Cannot find module '{alias}/{path}'`, even with alias paths defined in `tsconfig.json`. `typeorm` cli works fine with same settings and running the command with ts-node.

> I am quite new to typescript, else would have tried to fix it, opening a PR.

**Comment by luisramirez-m** [comment]
Hey, I had the same problem. I do not have much experience, but reading i finded a "solution" [tsconfig-path](https://www.npmjs.com/package/tsconfig-paths), in general we need to register the "alias paths" before so that typeorm-seeder can perform its function.

After installing "tsconfig-path", just change my command in package.json to:

```
"seed": "ts-node --project ./tsconfig.json -r tsconfig-paths/register ./node_modules/typeorm-seeding/dist/cli.js --config ./seeder.json seed"
```

and now it works!

**Comment by Shub1427** [comment]
Yeah! It works using `tsconfig-paths/register`. Thanks @luisramirez-m
