### ISSUE TITLE
Cannot load seeds when `__dirname` is in path

### ISSUE THREAD

**Issue by Pegase745** [w3tecch/typeorm-seeding#31]
As seen on the TypeOrm [documentation](https://typeorm.io/), one can use `__dirname` for the path to entities and stuff.

`loadFiles` util function, probably due to the use of `process.cwd()`, doesn't load any seeds if the path is declared as such:
```js
{
  // ormconfig.js
  seeds: [`${__dirname}/seeds/*.js`],
  ...
}
``` 

Any input on that ?

**Comment by diegoazh** [comment]
Hello @Pegase745 use `resolve` like this

```typescript
import { resolve } from "path";

export const ORMConfig = {
 // ...
  seeds: [
    resolve(__dirname, './seeds/**/*.seed.ts'),
  ],
  factories: [
    resolve(__dirname, './factories/**/*.factory.ts'),
  ],
// ...
};
```

**Comment by bpatram** [comment]
I'm also affected by this. It seems when loading the seed and factories an assumption is made that the path is relative.

https://github.com/w3tecch/typeorm-seeding/blob/9b614d4c74871204e30ec69f298ccb012e5ed108/src/utils/file.util.ts#L6-L10 _notice the join with `process.cwd()` on line 8_

If we dig into TypeORM's implementation in how they resolve files (like entities, migrations, etc) you'll notice they do a simple check to see if the path is absolute (ie, the path has a leading slash), and if it is then they don't prepend to it.

https://github.com/typeorm/typeorm/blob/442bff950704443e0b42fd0f950180d062f8389f/src/connection/ConnectionOptionsReader.ts#L145-L153

TypeORM seeding should most likely also follow this convention. Another potential issue I see is that this library prepends relative paths with the current working directory (cwd) rather than from the package root directory (or the directory containing the ormconfig file).

**Comment by bpatram** [comment]
@diegoazh your solution will not work since the paths defined must be relative, not absolute ones like you get when calling `resolve`.

@Pegase745 Here is the hacky workaround I am using until this issue is resolved. Using your example, you can do something like:

```js
// ormconfig.js

const relativeToSystemRoot = path.join(...process.cwd().split(path.sep).map(() => '..'));

module.exports = {
  seeds: [`${relativeToSystemRoot}/${__dirname}/seeds/*.js`],
  // ...
};
```
Obviously, this example is a bit contrived... but in some cases this is needed (like when the root to your config is different than your cwd (eg, monorepos).

---

Since the seeds and factories paths are always going to be prefixed with the cwd we can just work backwards from there in order to still resolve using your absolute path.

For the sake of example, let's say `process.cwd()` returns `'/Volumes/data/my_project'`, the file we want to reference is at `'/Volumes/data/my_project/seeds/*.js'`, and that our ormconfig.js file exists at `'/Volumes/data/my_project/ormconfig.js'`.

 
`relativeToSystemRoot` simply transforms the cwd path that into `'../../../..'`. This path simply works our way back up to a directory _above_ the root directory (`/`). From there we can append the absolute path to our file. Once typeorm-seeding goes to fetch the files it will have a path like this: `'/Volumes/data/my_project/../../../..//Volumes/data/my_project/seeds/*.js'`. This resolves to our absolute path as we would expect! (phew)

**Comment by hirsch88** [comment]
hi @bpatram thanks for the tip. :-)

I now use the ConnectionOptionReader of TypeORM.
Check out the new version 1.4.0

**Comment by aledoroshenko** [comment]
I'm having the same issue with this config:

```
import { TypeOrmModuleOptions } from '@nestjs/typeorm';

const typeOrmConfig: TypeOrmModuleOptions = {
  type: 'postgres',
  host: 'localhost',
  port: 5432,
  username: 'postgres',
  password: 'postgres',
  database: 'payments',
  entities: [__dirname + '/../**/*.entity.{js,ts}'],
  synchronize: true,
};

// Need this to make typeorm-seeder work, otherwise driver:undefined
// https://github.com/typeorm/typeorm/issues/4068
module.exports = typeOrmConfig
```

After `yarn run seed:run` (which is ` ts-node ./node_modules/typeorm-seeding/dist/cli.js seed --configName typeorm.config.ts`) it stuck on a database connection step and fail with this error:

```
✖ Database connection failed! Check your typeORM config file.
../nest-master/integration/typeorm/src/photo/photo.entity.ts:1:56 - error TS2307: Cannot find module 'typeorm' or its corresponding type declarations.

1 import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';
                                                         ~~~~~~~~~

error Command failed with exit code 1.
```

If i remove `__dirname` everything works.
