### ISSUE TITLE
Could update faker version 4 to 5 ?

### ISSUE THREAD

**Issue by SecondDim** [w3tecch/typeorm-seeding#98]

**Comment by tsubik** [comment]
In my opinion, faker should not be listed as a dependency for this library as it has nothing to do with seeding. Not sure what is the point of just passing it to the entity factory.

**Comment by sdr0x07b6** [comment]
I wrote about this in the Issue https://github.com/w3tecch/typeorm-seeding/issues/135 I just posted.
If the Faker passed by typorm-seeding is the singleton instance, it may be possible to guarantee unique values in the future.

`await factory(User)().makeMany(10)`

If it always gives you the same faker instance during the 10 iterations, then you can check for uniqueness in the instance.

If you import and use your own falers in the factory code, I don't think you can check if the value has already been generated before, because a new faker instance is used every time the factory is executed.

**Comment by sdr0x07b6** [comment]
It seems I should revise my perception.

I thought that if I didn't pass the only faker within the seeding run as an argument, then I wouldn't be able to determine uniqueness because each time I run the factory, it would use a new instance of the faker.
 
However, after being advised and trying in another issue https://github.com/w3tecch/typeorm-seeding/issues/135, it seems that unique values were generated.
Furthermore, I've had multiple successes generating 50,000 unique emails, so I think it's hard to say they all succeeded by accident.

It may not make sense to use a singleton faker.

---

However, there may be other advantages.
The factory and the faker are not intrinsically related.
but, if most people almost always use faker for factory,  if many people use faker almost exclusively for factories, it is often convenient to pass it as an argument without having to `require` it yourself.


In addition, Laravel, a well-known PHP framework that I know of, passes faker as an argument to factory as well.
I don't know the exact reason, but it seems to be in strong demand.

**Comment by NarHakobyan** [comment]
Hi guys, I've forked and removed faker from deps, you can use this repo as deps

https://github.com/NarHakobyan/typeorm-seed
